---
- name: Retrieve ocserv secrets from Vault
  community.hashi_vault.vault_read:
    url: "{{ vault_addr }}"
    token: "{{ vault_token }}"
    path: "{{ ocserv_vault_mount }}/data/{{ ocserv_vault_path }}"
  register: _vpn_users_secret
  delegate_to: localhost
  become: false
  run_once: true
  failed_when: false
  no_log: true

- name: Add users to list
  ansible.builtin.set_fact:
    _vpn_users_list: >-
      {{ _vpn_users_list | default([]) +
      [{'username': item.key,
      'password': item.value.password,
      'iroutes': item.value.iroutes | default(omit),
      'routes': item.value.routes | default(omit)}] }}
  loop: "{{ _vpn_users_secret.data.data.data | dict2items }}"
  when:
    - _vpn_users_secret is defined
    - _vpn_users_secret.data.data.data is defined
  delegate_to: localhost
  run_once: true
  become: false
  no_log: false
  vars:
    __item_display: "{{ item.key }}"
  loop_control:
    label: "{{ __item_display }}"

- name: Retrieve certs secrets from Vault
  community.hashi_vault.vault_read:
    url: "{{ vault_addr }}"
    token: "{{ vault_token }}"
    path: "{{ ocserv_certs_vault_mount }}/data/{{ ocserv_certs_vault_path }}"
  register: _ocserv_certs_vault_secret
  delegate_to: localhost
  become: false
  run_once: true
  failed_when: false
  no_log: true

- name: Set SSL certificate facts from Vault
  ansible.builtin.set_fact:
    _ocserv_ssl_certificate: >-
      {{ _ocserv_certs_vault_secret.data.data.data['certificate'] |
      default('') }}
    _ocserv_ssl_combined: >-
      {{ _ocserv_certs_vault_secret.data.data.data['combined'] |
      default('') }}
    _ocserv_ssl_private_key: >-
      {{ _ocserv_certs_vault_secret.data.data.data['private_key'] |
      default('') }}
  when: _ocserv_certs_vault_secret.data is defined
  no_log: true
