---
all:
  vars:
    ansible_user: svc-init

home-assistant:
  hosts:
    home-assistant-1:
      ansible_host: <hidden-ip>

meshcore:
  hosts:
    meshcore-1:
      ansible_host: <hidden-ip>
  vars:
    ansible_user: root

torserver:
  hosts:
    torserver-1:
      ansible_host: <hidden-ip>
  vars:
    ansible_user: root

nextcloud:
  hosts:
    nextcloud-1:
      ansible_host: <hidden-ip>
wg-vpn:
  hosts:
    wg-vpn-1:
      ansible_host: <hidden-ip>
  vars:
    ansible_user: tr1glav

certbot:
  children:
    nextcloud:
