---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable and start prometheus
  ansible.builtin.systemd:
    name: prometheus
    enabled: true
    state: restarted
