---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug-ubuntu-pod
  labels:
    app: my-ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debug-ubuntu-pod
  template:
    metadata:
      labels:
        app: debug-ubuntu-pod
    spec:
      containers:
        - name: debug-ubuntu-pod
          image: ubuntu:latest
          command: ["/bin/bash", "-c"]
          args:
            - |
              apt-get update && \
              apt-get install -y iputils-ping curl && \
              echo "Installation completed successfully!" && \
              sleep infinity
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
