---
- name: Retrieve secrets from Vault
  community.hashi_vault.vault_read:
    url: "{{ vault_addr }}"
    token: "{{ vault_token }}"
    path: "{{ haproxy_vault_mount }}/data/{{ haproxy_vault_path }}/keepalived"
  register: _haproxy_vault_keepalived_secret
  delegate_to: localhost
  become: false
  run_once: true
