---
- name: Retrieve secrets from Vault
  community.hashi_vault.vault_read:
    url: "{{ vault_addr }}"
    token: "{{ vault_token }}"
    path: "{{ meshcore_vault_mount }}/data/{{ meshcore_vault_path }}"
  register: _meshcore_vault_secret
  delegate_to: localhost
  become: false
  run_once: true
