---
- name: Configure resolved
  hosts: all
  become: true
  roles:
    - role: vm/resolved

- name: Configure logrotate
  hosts: all
  become: true
  roles:
    - vm/logrotate

- name: Configure routes
  hosts: nat-vms
  become: true
  roles:
    - vm/route