---
- name: Install k3s
  hosts: k3s
  become: true
  roles:
    - role: k3s

- name: Configure resolved
  hosts: k3s
  become: true
  roles:
    - role: vm/resolved

- name: Configure logrotate
  hosts: k3s
  become: true
  roles:
    - vm/logrotate
