---
prometheus_version: "2.51.2"
prometheus_user: "prometheus"
prometheus_group: "prometheus"
prometheus_dir: "/opt/prometheus"
prometheus_config_dir: "/etc/prometheus"
prometheus_refresh_interval: "5m"

# prometheus_url: >-
#   https://github.com/prometheus/prometheus/releases/download/v{{
#   prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz
prometheus_url: >-
  https://github-cache.{{ product_env }}.{{ domain }}
  /github/prometheus/prometheus/releases/download/v{{
  prometheus_version }}/prometheus-{{ prometheus_version
  }}.linux-amd64.tar.gz
