---
- name: Check kubeconfig exists
  ansible.builtin.stat:
    path: /etc/rancher/k3s/k3s.yaml
  register: k3s_kubeconfig_file

- name: Get kubeconfig
  ansible.builtin.slurp:
    src: /etc/rancher/k3s/k3s.yaml
  register: k3s_kubeconfig
  when:
    - k3s_mode == "server"
    - k3s_kubeconfig_file.stat.exists

- name: Write kubeconfig to local file
  ansible.builtin.copy:
    content: |
      {{ k3s_kubeconfig.content | b64decode | replace("<hidden-ip>", k3s_server_ip) }}
    dest: "{{ k3s_kubeconfig_local_path | default('~/.kube/clusters/%s.yaml' | format(k3s_server_ip)) }}"
    mode: "0600"
  delegate_to: localhost
  become: false
  when:
    - k3s_mode == "server"
    - k3s_kubeconfig_file.stat.exists
    - k3s_kubeconfig is defined
