---
all:
  vars:
    ansible_user: svc-init
router:
  hosts:
    router-1:
      ansible_host: <hidden-ip>

k3s:
  hosts:
    k3s-1:
      ansible_host: <hidden-ip>

certbot:
  children:
    router:
nat-vms:
  children:
    k3s:
