---
- name: Retrieve nextcloud secrets from Vault
  community.hashi_vault.vault_read:
    url: "{{ vault_addr }}"
    token: "{{ vault_token }}"
    path: "{{ nextcloud_vault_mount }}/data/{{ nextcloud_vault_path }}"
  register: _nextcloud_vault_secret
  delegate_to: localhost
  run_once: true
  failed_when: false
  become: false
  no_log: true

- name: Retrieve s3 secrets from Vault
  community.hashi_vault.vault_read:
    url: "{{ vault_addr }}"
    token: "{{ vault_token }}"
    path: "{{ nextcloud_s3_vault_mount }}/data/{{ nextcloud_s3_vault_path }}"
  register: _s3_vault_secret
  delegate_to: localhost
  become: false
  run_once: true
  failed_when: false
  no_log: true

- name: Retrieve certs secrets from Vault
  community.hashi_vault.vault_read:
    url: "{{ vault_addr }}"
    token: "{{ vault_token }}"
    path: >-
      {{ nextcloud_certs_vault_mount }}/data/{{
      nextcloud_certs_vault_path }}
  register: _nextcloud_certs_vault_secret
  delegate_to: localhost
  become: false
  run_once: true
  failed_when: false
  no_log: true

- name: Set nextcloud credentials facts
  ansible.builtin.set_fact:
    nextcloud_admin_user: >-
      {{ _nextcloud_vault_secret.data.data.data['admin_user'] }}
    nextcloud_admin_password: >-
      {{ _nextcloud_vault_secret.data.data.data['admin_password'] }}
    nextcloud_db_password: >-
      {{ _nextcloud_vault_secret.data.data.data['db_password'] }}
    nextcloud_db_root_password: >-
      {{ _nextcloud_vault_secret.data.data.data['db_root_password'] }}
  delegate_to: localhost
  become: false
  run_once: true
  when:
    - _nextcloud_vault_secret is defined

- name: Set S3 credentials facts (with combined access key)
  ansible.builtin.set_fact:
    _nextcloud_s3_access_key: >-
      {{ _s3_vault_secret.data.data.data['TENANT_ID'] }}:{{
      _s3_vault_secret.data.data.data['IAM_CLIENT_ID'] }}
    _nextcloud_s3_secret_key: >-
      {{ _s3_vault_secret.data.data.data['IAM_CLIENT_SECRET'] }}
  delegate_to: localhost
  become: false
  run_once: true
  when:
    - _s3_vault_secret is defined
    - _s3_vault_secret.data.data.data['TENANT_ID'] is defined
    - _s3_vault_secret.data.data.data['IAM_CLIENT_ID'] is defined
    - _s3_vault_secret.data.data.data['IAM_CLIENT_SECRET'] is defined

- name: Set SSL certificate facts from Vault
  ansible.builtin.set_fact:
    _nextcloud_ssl_certificate: >-
      {{ _nextcloud_certs_vault_secret.data.data.data['certificate'] |
      default('') }}
    _nextcloud_ssl_combined: >-
      {{ _nextcloud_certs_vault_secret.data.data.data['combined'] |
      default('') }}
    _nextcloud_ssl_private_key: >-
      {{ _nextcloud_certs_vault_secret.data.data.data['private_key'] |
      default('') }}
  when: _nextcloud_certs_vault_secret.data is defined
  no_log: true
