---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart etcd
  ansible.builtin.systemd:
    name: etcd
    state: restarted

- name: Reload systemd and restart etcd
  ansible.builtin.systemd:
    name: etcd
    state: restarted
    daemon_reload: true
