---
- name: Copy default config
  ansible.builtin.template:
    src: "prometheus.yml.j2"
    dest: "{{ prometheus_config_dir }}/prometheus.yml"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: '0644'

- name: Create systemd service
  ansible.builtin.template:
    src: "prometheus.service.j2"
    dest: "/etc/systemd/system/prometheus.service"
    mode: '0644'
  notify:
    - reload systemd
    - enable and start prometheus

- name: Ensure correct ownership of prometheus directory
  ansible.builtin.file:
    path: "{{ prometheus_dir }}"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    recurse: true

- name: Enable and start Prometheus service
  ansible.builtin.systemd:
    name: prometheus
    enabled: true
    state: started
    daemon_reload: true

- name: Cleanup temporary files
  ansible.builtin.file:
    path: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/"
    state: absent
  failed_when: false
