---
- name: Retrieve secrets from Vault
  community.hashi_vault.vault_read:
    url: "{{ vault_addr }}"
    token: "{{ vault_token }}"
    path: >-
      {{ openconnect_client_vault_mount }}/data/{{
      openconnect_client_vault_path }}
  register: _openconnect_client_secret
  delegate_to: localhost
  become: false
  run_once: true
  failed_when: false
  no_log: false
