---
- name: Retrieve secrets from Vault
  community.hashi_vault.vault_read:
    url: "{{ vault_addr }}"
    token: "{{ vault_token }}"
    path: "{{ s3_vault_mount }}/data/{{ env }}/s3_secrets"
  register: _s3_vault_secret
  delegate_to: localhost
  become: false
  run_once: true
  failed_when: false
  no_log: true

- name: Set S3 credentials facts (with combined access key)
  ansible.builtin.set_fact:
    s3_access_key: >-
      {{ _s3_vault_secret.data.data.data['TENANT_ID'] }}:{{
      _s3_vault_secret.data.data.data['IAM_CLIENT_ID'] }}
    s3_secret_key: "{{ _s3_vault_secret.data.data.data['IAM_CLIENT_SECRET'] }}"
  delegate_to: localhost
  become: false
  run_once: true
  when:
    - _s3_vault_secret is defined
    - _s3_vault_secret.data.data.data['TENANT_ID'] is defined
    - _s3_vault_secret.data.data.data['IAM_CLIENT_ID'] is defined
    - _s3_vault_secret.data.data.data['IAM_CLIENT_SECRET'] is defined
