---
apiVersion: v1
kind: Service
metadata:
  name: haproxy-loadbalancer
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
    - name: pgsql
      protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: haproxy
  type: LoadBalancer
