---
- name: Retrieve cloudflare secrets from Vault
  ansible.builtin.uri:
    url: "{{ vault_addr }}/v1/{{ certbot_vault_cf_mount
      }}/data/{{ certbot_vault_cf_path }}"
    method: GET
    headers:
      X-Vault-Token: "{{ vault_token }}"
    return_content: true
    validate_certs: false
  register: _certbot_vault_cf_secrets
  become: false
  no_log: false  # Changed from false to true for security
  failed_when: _certbot_vault_cf_secrets.status != 200

- name: Ensure KV v2 secrets engine is enabled
  ansible.builtin.command: |
    vault secrets enable -path=certs/{{ env }} kv-v2
  environment:
    VAULT_ADDR: "{{ vault_addr }}"
    VAULT_TOKEN: "{{ vault_token }}"
  register: enable_kv
  become: false
  failed_when:
    - enable_kv.rc != 0
    - "'path is already in use' not in enable_kv.stderr"
  changed_when: "'Success!' in enable_kv.stdout"
