---
- name: Check etcd cluster health
  ansible.builtin.command: >-
    etcdctl --endpoints=http://<hidden-ip>:{{
    etcd_client_port }} endpoint health
  environment:
    ETCDCTL_API: "3"
  register: __etcd_health
  until: __etcd_health.rc == 0
  retries: 15
  delay: 3
  changed_when: false

- name: Check etcd cluster status
  ansible.builtin.command: >-
    etcdctl --endpoints=http://<hidden-ip>:{{
    etcd_client_port }} endpoint status -w table
  environment:
    ETCDCTL_API: "3"
  register: _etcd_status
  changed_when: false

- name: Display etcd cluster health
  ansible.builtin.debug:
    msg: "etcd cluster health: {{ __etcd_health.stdout }}"

- name: Display etcd cluster status
  ansible.builtin.debug:
    msg: "etcd cluster status:\n{{ _etcd_status.stdout }}"

- name: Verify cluster membership
  ansible.builtin.command: >-
    etcdctl --endpoints=http://<hidden-ip>:{{
    etcd_client_port }} member list -w table
  environment:
    ETCDCTL_API: "3"
  register: __etcd_members
  changed_when: false

- name: Display cluster members
  ansible.builtin.debug:
    msg: "etcd cluster members:\n{{ __etcd_members.stdout }}"
