---
- name: Restart apache
  ansible.builtin.service:
    name: apache2
    state: restarted

- name: Reload apache
  ansible.builtin.service:
    name: apache2
    state: reloaded

- name: Restart postgresql
  ansible.builtin.service:
    name: postgresql
    state: restarted

- name: Rake db migrate
  ansible.builtin.command:
    cmd: "bundle exec rake db:migrate RAILS_ENV=production"
    chdir: "{{ redmine_install_dir }}"
  become: true
  become_user: "{{ redmine_user }}"
  changed_when: false

- name: Rake assets clobber
  ansible.builtin.command:
    cmd: "bundle exec rake assets:clobber RAILS_ENV=production"
    chdir: "{{ redmine_install_dir }}"
  become: true
  become_user: "{{ redmine_user }}"
  changed_when: false
